packages:
  - ./
  - playgrounds/*
  - test/fixtures/nitro-app
  - "!dux"
  - "!dux/**"

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: true

ignoreWorkspaceRootCheck: true
